name: Backup repo to S3
on:
  schedule:
    - cron: 0 20 * * 5 # Backup at 8 pm Fridays
  workflow_dispatch:

jobs:
  s3Backup:
    runs-on: ubuntu-latest
    environment: artifacts

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: rocketreach/github-actions/backup@main
